version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabasename
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 8081:3306
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
        volume:
          nocopy: true


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-data:



